### ISSUE TITLE
Is there a way to contact you?

### ISSUE THREAD

**Issue by ftk789** [VDiPaola/Emotes-ChromeExtension#1]
Nvm it works I'm just stupid I had a couple scripts messing around with the manifest

**Comment by ftk789** [comment]
Also is there a way to contact you?

**Comment by VDiPaola** [comment]
I quickly rewrote some of it for manifest 3 using webpack, if you want to contact me my discord is Enzo#3825

**Comment by ftk789** [comment]
Thank you for your help, I have another question, How to bypass the " Whitelist/ Blacklist " function, Just like whitelist automatically on all websites?

**Comment by VDiPaola** [comment]
whitelist = always disabled unless site is in whitelist array. blacklist = always enabled unless site is in blacklist array. Hope that answers the question.

**Comment by ftk789** [comment]
Thank you very much for an really good project.
